compile:
	coffee -c gyazz_readwrite.coffee
	coffee -c gyazz_buffer.coffee
	coffee -c gyazz_lib.coffee
	coffee -c gyazz_related.coffee
	coffee -c gyazz_tag.coffee
	coffee -c gyazz_notification.coffee
	coffee -c gyazz.coffee
